#!/bin/sh

[ "$ACTION" = add ] || exit

for NIC in $(ls /sys/class/net/)
do
  if command -v ethtool &> /dev/null && ethtool $NIC &> /dev/null; then
    RX_MAX=$(ethtool -g $NIC 2>/dev/null | awk '/^RX:/ {print $2}' | awk 'NR==1')
    TX_MAX=$(ethtool -g $NIC 2>/dev/null | awk '/^TX:/ {print $2}' | awk 'NR==1')

    if [ -z "$RX_MAX" ] || [ -z "$TX_MAX" ]; then
      continue
    fi

    ethtool -G $NIC rx $RX_MAX
    ethtool -G $NIC tx $TX_MAX
  fi
done
