#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=15

boot() {
	[ ! -f /sys/devices/system/cpu/intel_pstate/status ] && return 1

	if [ "$(cat /sys/devices/system/cpu/intel_pstate/status)" = "passive" ]; then
		for i in $(find /sys/devices/system/cpu/cpu* -maxdepth 0 | grep -Eo '[0-9]+')
		do
			echo "ondemand" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
		done
	fi
}
