#!/bin/sh

device=`basename $DEVPATH`

case $device in
	mtdblock*|ubiblock*|zram*)
		exit 0
		;;
esac

case "$ACTION" in
	add)
		mkdir -p /usb/$device
		mount -o rw,noatime,discard /dev/$device /usb/$device
		if [ -f "/usb/$device/recovery.txt" ]; then
			echo y | firstboot
			sleep 2
			reboot
		else
			umount -l /usb/$device
			rm -rf /usb
		fi
		;;
esac
